version: '1.0.{build}'

pull_requests:
  do_not_increment_build_number: true

configuration:
- Debug
- Release

platform: Any CPU

before_build:
  nuget restore

cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  verbosity: minimal